sudo: required
language: python
services:
  - docker
cache: pip
python:
  - "3.6"
before_install:
  - python3 -m pip install -U flake8 flake8-quotes
install:
  - python3 -m pip install -r requirements.txt
script:
  - ./test.sh
